services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_app
    ports: ["5433:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    
  api:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ai_app
      PORT: 4000
    depends_on: [db]
    ports: ["4001:4000"]
volumes:
  pgdata: {}